export const Users = [
    {
        id: 1,
        profilePicture: "asserts / koreana_files / 10.jpeg",
        username: "Reone",
    },
    {
        id: 2,
        profilePicture: "asserts / koreana_files / 2.jpeg",
        username: "Reshu",
    },
    {
        id: 3,
        profilePicture: "asserts / koreana_files / 3.jpeg",
        username: "Mayra",
    },
    {
        id: 4,
        profilePicture: "asserts / koreana_files / 4.jpeg",
        username: "Nayra",
    },
    {
        id: 5,
        profilePicture: "asserts / koreana_files / 5.jpeg",
        username: "Kayra",
    },
    {
        id: 6,
        profilePicture: "asserts / koreana_files / 6.jpeg",
        username: "Ashu",
    },
    {
        id: 7,
        profilePicture: "asserts / koreana_files / 7.jpeg",
        username: "Richu",
    },
    {
        id: 8,
        profilePicture: "asserts / koreana_files / 8.jpeg",
        username: "Ashar",
    },
    {
        id: 9,
        profilePicture: "asserts / koreana_files / 9.jpeg",
        username: "Anjolie",
    },
];
export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "asserts / koreana_files / wp7373746.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/post/2.jpeg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "assets/post/3.jpeg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "assets/post/4.jpeg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "assets/post/5.jpeg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "assets/post/6.jpeg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "assets/post/7.jpeg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },

    {
        id: 8,
        photo: "assets/post/8.jpeg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "assets/post/9.jpeg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "assets/post/10.jpeg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
    {
        id: 11,
        desc: "I love you.",
        photo: "asserts /koreana_files /72695.png",
        date: "4 days ago",
        userId: 11,
        like: 82,
        comment: 4,
    },
    {
        id: 12,
        desc: "Your smile is best thing.",
        photo: "asserts / koreana_files / tokyo.jpg",
        date: "1 days ago",
        userId: 12,
        like: 85,
        comment: 7,
    },
    {
        id: 13,
        desc: "Love yourself.",
        photo: "asserts / koreana_files / thss.jpg",
        date: "2 days ago",
        userId: 13,
        like: 100,
        comment: 50,
    },
    {
        id: 14,
        desc: "Never regret anything that made you smile.",
        photo: "asserts / koreana_files / wp.jpg",
        date: "8 days ago",
        userId: 14,
        like: 90,
        comment: 80,
    },
    {
        id: 15,
        desc: "Shine through the dark.",
        photo: "asserts / koreana_files / wp.jpg",
        date: "9 days ago",
        userId: 15,
        like: 82,
        comment: 418,
    },
    {
        id: 16,
        desc: "Never regret anything that made you smile.",
        photo: "asserts / koreana_files / wp.jpg",
        date: "15 days ago",
        userId: 16,
        like: 10,
        comment: 10,
    },
    {
        id: 17,
        desc: "You made my days.",
        photo: "asserts / koreana_files / thr.jpg",
        date: "4 days ago",
        userId: 17,
        like: 101,
        comment: 17,
    },
    {
        id: 18,
        desc: "Love your dream more than people.",
        photo: "asserts / koreana_files / Anime.jpg",
        date: " 15 mins ago",
        userId: 18,
        like: 1000,
        comment: 78,
    },
    {
        id: 19,
        desc: "Love the way you Lie",
        photo: "asserts / koreana_files / 516664.jpg",
        date: "4 days ago",
        userId: 19,
        like: 82,
        comment: 4,
    },
    {
        id: 20,
        desc: "It's ohk to not be ohk",
        photo: "asserts / koreana_files / 533007.png",
        date: "4 days ago",
        userId: 20,
        like: 120,
        comment: 4,
    },
    {
        id: 21,
        desc: "Be addicted to loving yourself",
        photo: "asserts / koreana_files / 545909.jpg",
        date: "4 days ago",
        userId: 21,
        like: 176,
        comment: 104,
    },


];
